const nigerianBanks = [
  { name: 'Access Bank', code: '044', slug: 'access-bank' },
  { name: 'Citibank Nigeria', code: '023', slug: 'citibank-nigeria' },
  { name: 'Diamond Bank', code: '063', slug: 'diamond-bank' },
  { name: 'Ecobank Nigeria', code: '050', slug: 'ecobank-nigeria' },
  { name: 'Fidelity Bank', code: '070', slug: 'fidelity-bank' },
  { name: 'First Bank of Nigeria', code: '011', slug: 'first-bank-of-nigeria' },
  { name: 'First City Monument Bank', code: '214', slug: 'first-city-monument-bank' },
  { name: 'Guaranty Trust Bank', code: '058', slug: 'guaranty-trust-bank' },
  { name: 'Heritage Banking Company Ltd.', code: '030', slug: 'heritage-banking-company-ltd' },
  { name: 'Keystone Bank', code: '082', slug: 'keystone-bank' },
  { name: 'Skye Bank', code: '076', slug: 'skye-bank' },
  { name: 'Stanbic IBTC Bank', code: '221', slug: 'stanbic-ibtc-bank' },
  { name: 'Standard Chartered Bank', code: '068', slug: 'standard-chartered-bank' },
  { name: 'Sterling Bank', code: '232', slug: 'sterling-bank' },
  { name: 'Union Bank of Nigeria', code: '032', slug: 'union-bank-of-nigeria' },
  { name: 'United Bank for Africa', code: '033', slug: 'united-bank-for-africa' },
  { name: 'Unity Bank', code: '215', slug: 'unity-bank' },
  { name: 'Wema Bank', code: '035', slug: 'wema-bank' },
  { name: 'Zenith Bank', code: '057', slug: 'zenith-bank' },
  { name: 'Jaiz Bank', code: '301', slug: 'jaiz-bank' },
  { name: 'Suntrust Bank', code: '100', slug: 'suntrust-bank' },
  { name: 'Providus Bank', code: '101', slug: 'providus-bank' },
  { name: 'Parallex Bank', code: '104', slug: 'parallex-bank' },
  { name: 'Polaris Bank', code: '076', slug: 'polaris-bank' },
  { name: 'Titan Trust Bank', code: '102', slug: 'titan-trust-bank' },
  { name: 'TAJ Bank', code: '302', slug: 'taj-bank' },
  { name: 'Lotus Bank', code: '303', slug: 'lotus-bank' },
  { name: 'Kuda Bank', code: '090267', slug: 'kuda-bank' },
  { name: 'VFD Microfinance Bank', code: '566', slug: 'vfd-microfinance-bank' },
  { name: 'Rubies MFB', code: '125', slug: 'rubies-mfb' },
  { name: 'ALAT by WEMA', code: '035A', slug: 'alat-by-wema' },
  { name: 'Opay', code: '999992', slug: 'opay' },
  { name: 'PalmPay', code: '999991', slug: 'palmpay' },
  { name: 'Carbon', code: '565', slug: 'carbon' },
  { name: 'FairMoney', code: '090435', slug: 'fairmoney' }
];

module.exports = nigerianBanks;